[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
flatbuffers = "25.2.10"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
shared = { path = "../shared" }
